spring:
  datasource:
    url: jdbc:h2:mem:blog-application
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: true
server:
  servlet:
    context-path: /api
