spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost/blog_application
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
  liquibase:
    change-log: db/changelog/master.xml
server:
  servlet:
    context-path: /api

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    url: /api.yml
