version: '3.8'

services:
  database:
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: blog_application
    ports:
      - "5432:5432"
    container_name: blog_application_database
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/mlas/tutorial/blog-application'
