version: '3.8'

services:
  database:
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: blog_application
    ports:
      - "5432:5432"
    container_name: blog_application_database
    volumes:
      - db-data:/var/lib/postgresql/data
  application:
    image: blog-application:1.0-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database/blog_application
    container_name: blog_application

volumes:
  db-data:
